ig.module('game.gamestate.level-setup').
defines(function(){
	var r = 'A';
	var b = 'B';
	var X = null;

	ig.LevelSetup = [
	{
		name: "first steps",
		blocks: [
				[X,X,X,X,X,X,b],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,b,X,b,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,b,X,b,X,b,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
		],
	},
	{
		name: "lines",
		blocks: [
				[b,b,b,b,b,b,b],
				[X,X,X,X,X,X,X],
				[b,b,b,b,b,b,b],
				[X,X,X,X,X,X,X],
				[b,b,b,b,b,b,b],
				[X,X,X,X,X,X,X],
				[b,b,b,b,b,b,b],
				[X,X,X,X,X,X,X],
				[b,b,b,b,b,b,b],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "vertical",
		blocks: [
				[b,X,b,X,b,X,b],
				[b,X,b,X,b,X,b],
				[b,X,b,X,b,X,b],
				[b,X,b,X,b,X,b],
				[b,X,b,X,b,X,b],
				[b,X,b,X,b,X,b],
				[b,X,b,X,b,X,b],
				[b,X,b,X,b,X,b],
				[b,X,b,X,b,X,b],
				[b,X,b,X,b,X,b]
		],
	},
	{
		name: "invaders",
		blocks: [
				[X,b,X,X,X,b,X],
				[X,X,b,X,b,X,X],
				[X,b,b,b,b,b,X],
				[b,b,X,b,b,X,b],
				[b,b,b,b,b,b,b],
				[b,X,b,b,b,X,b],
				[b,X,b,X,b,X,b],
				[X,X,b,X,b,X,X]
		],
	},
	{
		name: "ribcage",
		blocks: [
				[X,b,b,b,b,b,X],
				[b,X,X,b,X,X,b],
				[X,b,b,b,b,b,X],
				[b,X,X,b,X,X,b],
				[X,b,b,b,b,b,X],
				[b,X,X,b,X,X,b],
				[X,b,b,b,b,b,X],
				[b,X,X,b,X,X,b],
				[X,b,b,b,b,b,X],
				[b,X,X,X,X,X,b],
				[b,X,b,X,b,X,b],
				[X,b,X,X,X,b,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "brick wall",
		blocks: [
				[X,b,X,b,X,b,X],
				[X,X,X,X,X,X,X],
				[X,X,b,X,b,X,X],
				[X,X,X,X,X,X,X],
				[X,b,X,b,X,b,X],
				[X,X,X,X,X,X,X],
				[X,X,b,X,b,X,X],
				[X,X,X,X,X,X,X],
				[X,b,X,b,X,b,X],
				[X,X,X,X,X,X,X],
				[X,X,b,X,b,X,X],
				[X,X,X,X,X,X,X],
				[X,b,X,b,X,b,X],
				[X,X,X,X,X,X,X],
				[X,X,b,X,b,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "triforce",
		blocks: [
				[X,X,X,b,X,X,X],
				[X,X,X,b,X,X,X],
				[X,X,b,b,b,X,X],
				[X,X,b,b,b,X,X],
				[X,b,X,X,X,b,X],
				[X,b,X,X,X,b,X],
				[b,b,b,X,b,b,b],
				[b,b,b,b,b,b,b],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "ff",
		blocks: [
				[b,b,b,b,X,b,b],
				[b,b,b,b,X,b,b],
				[b,b,b,b,X,b,b],
				[b,b,b,b,X,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,b,X,b,b],
				[b,b,X,b,X,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,b,b,b,b],
				[b,b,X,b,b,b,b],
				[b,b,X,b,b,b,b],
				[b,b,X,b,b,b,b],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "star",
		blocks: [
				[X,X,X,b,X,X,X],
				[X,X,X,b,X,X,X],
				[X,X,b,b,b,X,X],
				[X,X,b,b,b,X,X],
				[b,b,b,b,b,b,b],
				[b,b,b,b,b,b,b],
				[X,b,b,b,b,b,X],
				[X,X,b,b,b,X,X],
				[X,X,b,b,b,X,X],
				[X,X,b,b,b,X,X],
				[X,b,b,b,b,b,X],
				[X,b,b,X,b,b,X],
				[X,b,X,X,X,b,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "opera",
		blocks: [
				[X,X,b,b,b,X,X],
				[X,b,b,b,b,b,X],
				[X,b,b,b,b,b,X],
				[b,b,b,X,b,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,X,X,b,b],
				[b,b,b,X,b,b,b],
				[X,b,b,b,b,b,X],
				[X,b,b,b,b,b,X],
				[X,X,b,b,b,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "circles",
		blocks: [
				[X,b,b,b,b,b,X],
				[b,X,X,X,X,X,b],
				[X,X,b,b,b,X,X],
				[X,b,X,X,X,b,X],
				[b,X,X,b,X,X,b],
				[b,X,b,X,b,X,b],
				[b,X,X,b,X,X,b],
				[X,b,X,X,X,b,X],
				[X,X,b,b,b,X,X],
				[b,X,X,X,X,X,b],
				[X,b,b,b,b,b,X],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "rocket",
		blocks: [
				[X,X,X,b,X,X,X],
				[X,X,b,X,b,X,X],
				[X,X,b,X,b,X,X],
				[X,b,X,b,X,b,X],
				[X,b,X,b,X,b,X],
				[X,b,X,X,X,b,X],
				[X,b,X,X,X,b,X],
				[X,b,X,X,X,b,X],
				[X,b,X,X,X,b,X],
				[X,b,X,X,X,b,X],
				[b,b,X,X,X,b,b],
				[b,b,X,X,X,b,b],
				[X,X,b,b,b,X,X],
				[X,X,b,X,b,X,X],
				[X,b,X,b,X,b,X],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "tweet",
		blocks: [
				[X,X,X,X,b,X,X],
				[X,X,X,X,b,X,X],
				[X,X,X,b,b,b,X],
				[X,X,X,b,b,b,X],
				[X,X,X,b,b,b,b],
				[X,X,X,b,b,b,X],
				[X,X,X,b,b,b,X],
				[b,b,b,b,b,b,X],
				[b,b,b,b,b,b,X],
				[X,b,b,b,b,b,X],
				[X,b,b,b,b,b,X],
				[X,X,b,b,b,X,X],
				[X,X,b,b,b,X,X],
				[X,b,b,b,b,X,X],
				[X,b,b,b,b,X,X],
				[b,b,b,b,X,X,X],
				[b,b,b,b,X,X,X],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "1up",
		blocks: [
				[X,X,X,b,X,X,X],
				[X,X,b,X,b,X,X],
				[X,b,X,X,X,b,X],
				[b,X,X,X,X,X,b],
				[b,X,X,X,X,X,b],
				[b,X,X,X,X,X,b],
				[b,b,b,b,b,b,b],
				[X,b,b,b,b,b,X],
				[X,b,X,b,X,b,X],
				[X,b,X,b,X,b,X],
				[X,b,b,b,b,b,X],
				[X,X,b,b,b,X,X]
		],
	},
	{
		name: "castle",
		blocks: [
				[b,X,b,X,b,X,b],
				[b,X,b,X,b,X,b],
				[b,b,b,b,b,b,b],
				[b,X,b,b,b,X,b],
				[b,b,b,b,b,b,b],
				[b,b,b,b,b,b,b],
				[b,X,b,b,b,X,b],
				[b,b,b,b,b,b,b],
				[b,b,b,b,b,b,b],
				[b,X,b,b,b,X,b],
				[b,b,b,b,b,b,b],
				[b,b,b,X,b,b,b],
				[b,b,X,X,X,b,b],
				[b,b,X,X,X,b,b],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "checkers",
		blocks: [
				[b,X,b,X,b,X,b],
				[X,b,X,b,X,b,X],
				[b,X,b,X,b,X,b],
				[X,b,X,b,X,b,X],
				[b,X,b,X,b,X,b],
				[X,b,X,b,X,b,X],
				[b,X,b,X,b,X,b],
				[X,b,X,b,X,b,X],
				[b,X,b,X,b,X,b],
				[X,b,X,b,X,b,X],
				[b,X,b,X,b,X,b],
				[X,b,X,b,X,b,X],
				[b,X,b,X,b,X,b],
		],
	},
	{
		name: "1GAM",
		blocks: [
				[X,b,X,X,r,r,r],
				[b,b,X,X,r,X,X],
				[X,b,X,X,r,X,r],
				[X,b,X,X,r,X,r],
				[X,b,X,X,r,r,r],
				[X,X,X,X,X,X,X],
				[r,r,r,X,r,X,r],
				[r,X,r,X,r,r,r],
				[r,X,r,X,r,r,r],
				[r,r,r,X,r,X,r],
				[r,X,r,X,r,X,r]
		],
	},
	{
		name: "pacman",
		blocks: [
				[X,X,X,b,b,X,X],
				[X,X,b,b,b,b,X],
				[X,X,b,b,b,b,X],
				[X,b,b,X,b,b,b],
				[X,b,b,b,b,b,b],
				[b,b,b,b,b,b,X],
				[b,b,b,b,b,X,X],
				[b,b,b,b,X,X,X],
				[b,b,b,b,X,X,X],
				[b,b,b,b,b,X,X],
				[b,b,b,b,b,b,X],
				[X,b,b,b,b,b,b],
				[X,b,b,b,b,b,b],
				[X,X,b,b,b,b,X],
				[X,X,b,b,b,b,X],
				[X,X,X,b,b,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "squares",
		blocks: [
				[b,b,b,b,b,b,b],
				[b,b,b,b,b,b,b],
				[b,b,b,b,b,b,b],
				[b,X,X,X,X,X,b],
				[b,X,X,X,X,X,b],
				[b,X,b,b,b,X,b],
				[b,X,b,b,b,X,b],
				[b,X,b,X,b,X,b],
				[b,X,b,X,b,X,b],
				[b,X,b,b,b,X,b],
				[b,X,b,b,b,X,b],
				[b,X,X,X,X,X,b],
				[b,X,X,X,X,X,b],
				[b,b,b,b,b,b,b],
				[b,b,b,b,b,b,b],
				[b,b,b,b,b,b,b],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "kong",
		blocks: [
				[b,X,b,b,b,b,b],
				[X,X,X,X,X,X,X],
				[b,b,b,b,b,X,b],
				[X,X,X,X,X,X,X],
				[b,b,b,X,b,b,b],
				[X,X,X,X,X,X,X],
				[b,b,b,b,b,X,b],
				[X,X,X,X,X,X,X],
				[b,X,b,b,b,b,b],
				[X,X,X,X,X,X,X],
				[X,b,b,b,b,b,b],
				[X,X,X,X,X,X,X],
				[b,b,b,b,b,X,b],
				[X,X,X,X,X,X,X],
				[b,b,b,b,b,b,X],
				[b,b,b,b,b,b,b],
				[b,b,b,b,b,b,b],
				[X,X,X,X,X,X,X]
		],
	},
	{
		name: "grats",
		blocks: [
				[X,X,X,X,X,X,X],
				[X,b,X,X,X,b,X],
				[X,b,X,X,X,b,X],
				[X,b,X,X,X,b,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X],
				[X,b,b,b,b,b,X],
				[X,b,b,b,b,b,X],
				[X,b,b,b,b,b,X],
				[X,b,b,b,b,b,X],
				[X,X,b,b,b,X,X],
				[X,X,b,b,b,X,X],
				[X,X,X,b,X,X,X],
				[X,X,X,X,X,X,X],
				[X,X,X,X,X,X,X]
		],
	}
	];
});
